### ISSUE TITLE
Error when running Test Project in GUI

### ISSUE THREAD

**Issue by vlv-vm** [sequence-toolbox/SeQUeNCe#161]
Hello,

When trying to run the Test project in SeQUeNCe GUI I get an error.

Steps to reproduce:
- Start flask app through terminal as per documentation
- While in SeQUeNCe web app, open Run tab; add Name and Time; set logging options to Info; Run

After running the simulation, terminal output looks like this:

ubuntuvm@ubuntuvm-virtual-machine:~/Desktop/sequence/SeQUeNCe$ python3 gui.py
Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'sequence.gui.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
127.0.0.1 - - [28/Mar/2023 10:24:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:07] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:07] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:07] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 204 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 204 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [28/Mar/2023 10:24:08] "POST /_dash-update-component HTTP/1.1" 200 -
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/dash/dash.py", line 1273, in dispatch
    ctx.run(
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/dash/_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/sequence/gui/app.py", line 1042, in run_sim
    if not self.simulation.timeline.is_running:
AttributeError: 'QuantumGUI' object has no attribute 'simulation'
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/dash/dash.py", line 1273, in dispatch
    ctx.run(
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/dash/_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/ubuntuvm/.local/lib/python3.10/site-packages/sequence/gui/app.py", line 1042, in run_sim
    if not self.simulation.timeline.is_running:
AttributeError: 'QuantumGUI' object has no attribute 'simulation'
127.0.0.1 - - [28/Mar/2023 10:24:20] "POST /_dash-update-component HTTP/1.1" 500 -

Based on the error I checked https://github.com/sequence-toolbox/SeQUeNCe/blob/master/src/gui/app.py, and noticed that simulation attribute is not implemented. Is there a quick fix to get this simulation up and running or an approximate ETA for this feature?

Thank you.

**Comment by LydiaNosali** [comment]
I got the same problem. The _self.simulation_ is actually commented, I tried to uncomment and run, but it gives other errors that require change in the code of the node class, so I stopped there. Is there a way to update the Gui to the new architecture of sequence?
