### ISSUE TITLE
Code gathered from Tutorial's Chapter 4 crashes

### ISSUE THREAD

**Issue by viachesl** [sequence-toolbox/SeQUeNCe#58]
I just gathered the code from Chapter 4 as follows:
```
import sys, time
sys.path.append( '../' )

#from typing import TYPE_CHECKING, Any

from sequence.kernel.timeline import Timeline
from sequence.topology.node import Node
from sequence.topology.node import BSMNode
from sequence.components.memory import MemoryArray
from sequence.resource_management.resource_manager import ResourceManager
from sequence.entanglement_management.generation import EntanglementGenerationA
from sequence.components.optical_channel import ClassicalChannel, QuantumChannel
from sequence.resource_management.rule_manager import Rule

import numpy as np

#__seed = int( time.time() * 1000 ) % 2**32
np.random.seed(0)

class RouterNode(Node):
    def __init__(self, name, tl, memo_size=50):
        super().__init__(name, tl)
        self.memory_array = MemoryArray(name + ".MemoryArray", tl, num_memories=memo_size)
        self.memory_array.owner = self
        self.resource_manager = ResourceManager(self)

    def receive_message(self, src: str, msg: "Message") -> None:
        if msg.receiver == "resource_manager":
            self.resource_manager.received_message(src, msg)
        else:
            if msg.receiver is None:
                matching = [p for p in self.protocols if type(p) == msg.protocol_type]
                for p in matching:
                    p.received_message(src, msg)
            else:
                for protocol in self.protocols:
                    if protocol.name == msg.receiver:
                        protocol.received_message(src, msg)
                        break

    def get_idle_memory(self, info: "MemoryInfo") -> None:
        pass

def eg_rule_condition_f1(memory_info: "MemoryInfo", manager: "MemoryManager"):
    if memory_info.state == "RAW" and memory_info.index < 10:
        return [memory_info]
    else:
        return []

# router 1 action
def eg_rule_action_f1_1(memories_info: "List" ):
    def req_func(protocols):
        for protocol in protocols:
            if isinstance(protocol, EntanglementGenerationA) and protocol.other == "r1" and r2.memory_array.memories.index(protocol.memory) < 10:
                return protocol

    memories = [info.memory for info in memories_info]
    memory = memories[0]
    protocol = EntanglementGenerationA(None, "EGA." + memory.name, "m12", "r2", memory)
    return [protocol, ["r2"], [req_func]]

# router 2 action
#def eg_rule_action_f1_2(memories_info: List["MemoryInfo"]):
def eg_rule_action_f1_2(memories_info: "List" ):
    memories = [info.memory for info in memories_info]
    memory = memories[0]
    protocol = EntanglementGenerationA(None, "EGA." + memory.name, "m12", "r1", memory)
    return [protocol, [None], [None]]

runtime = 10e12
tl = Timeline(runtime)

# nodes
r1 = RouterNode("r1", tl, memo_size=20)
r2 = RouterNode("r2", tl, memo_size=40)
r3 = RouterNode("r3", tl, memo_size=10)

m12 = BSMNode("m12", tl, ["r1", "r2"])
m23 = BSMNode("m23", tl, ["r2", "r3"])

# create all-to-all classical connections
cc_delay = 1e9
node_list = [r1, r2, r3, m12, m23]
for i, node1 in enumerate(node_list):
    for node2 in node_list[i+1:]:
        cc = ClassicalChannel("cc_%s_%s"%(node1.name, node2.name), tl, 1e3, delay=cc_delay)
        cc.set_ends(node1, node2)

# create quantum channels linking r1 and r2 to m1
qc_atten = 0
qc_dist = 1e3
qc1 = QuantumChannel("qc_r1_m12", tl, qc_atten, qc_dist)
qc1.set_ends(r1, m12)
qc2 = QuantumChannel("qc_r2_m12", tl, qc_atten, qc_dist)
qc2.set_ends(r2, m12)
# create quantum channels linking r2 and r3 to m2
qc3 = QuantumChannel("qc_r2_m23", tl, qc_atten, qc_dist)
qc3.set_ends(r2, m23)
qc4 = QuantumChannel("qc_r3_m23", tl, qc_atten, qc_dist)
qc4.set_ends(r3, m23)

tl.init()

# load rules
rule1 = Rule(10, eg_rule_action_f1_1, eg_rule_condition_f1)
r1.resource_manager.load(rule1)
rule2 = Rule(10, eg_rule_action_f1_2, eg_rule_condition_f1)
r2.resource_manager.load(rule2)

tl.run()

print("Router 1 Memories")
print("Index:\tEntangled Node:\tFidelity:\tEntanglement Time:")
for i, info in enumerate(r1.resource_manager.memory_manager):
    print("{:6}\t{:15}\t{:9}\t{}".format(str(i), str(info.remote_node),
                                         str(info.fidelity), str(info.entangle_time * 1e-12)))

``` 
and it throws the error somewhere deep in Sequence:
```
Traceback (most recent call last):
  File "...\SeQUeNCe-master\scripts\resource-management.py", line 110, in <module>
    tl.run()
  File "..\sequence\kernel\timeline.py", line 113, in run
    event.process.run()
  File "..\sequence\kernel\process.py", line 30, in run
    return getattr(self.owner, self.activation)(*self.act_params)
  File "...\SeQUeNCe-master\scripts\resource-management.py", line 29, in receive_message
    self.resource_manager.received_message(src, msg)
  File "..\sequence\resource_management\resource_manager.py", line 228, in received_message
    self.owner.send_message(src, new_msg)
  File "..\sequence\topology\node.py", line 98, in send_message
    self.cchannels[dst].transmit(msg, self, priority)
KeyError: 'r1'
```
Please, help me to fix this. Sorry, it seems py-file attaching here is prohibited, so pasting it as text again. Thanks!

**Comment by xwu64** [comment]
Sorry for misleading. The reason is that the classical channel is changed from the undirected channel to the directed channel. We change the code in the script `two_flow.py` and forget update code in the markdown file. I'll change it soon. 

Thanks for point out!
